### ISSUE TITLE
Set out structure for processing user queries

### ISSUE THREAD

**Issue by woodwardmw** [BibleNLP/assistant.bible#3]
## File Structure
Suggesting the following structure:

app
├──  core
 |        ├── interface.py
 |        ├── vanilla.py
 |        ├── langchain.py

## Functions
`add_file_to_collection(file: File, database_tech: str, **kwargs) -> None:`
    # Get embeddings from the file and add them to the database, along with metadata.
    # We'll need to decide what files we accept. If we want the demo to run on translation helps, those are currently in CSV, XML and SFM formats.

`translate_text(text: str, translation_api: str, **kwargs) -> Tuple(english_text: str, identified_lang: str):`
    # Uses a translation API (e.g. google translate) to translate text to English and identify the original language

`get_results_from_query(query: str, chat_stat: List[dict], k: int, **kwargs) -> match_results: List[dict]:`
    # Queries a collection and returns the top k results as a list of dicts

`create_context(match_results: List[dict], **kwargs) -> context: str:`
    # Take the list of match results and create the string context for the prompt

`query_llm(prompt: str, context: str, chat_state: List[dict], model: str, **kwargs) -> response:`
    # Takes the context and the chat state history and create the prompt to send to the LLM
    # Takes the prompt and queries the LLM, returning the response

`process_llm_response(response,**kwargs) -> message: str:`
    # Takes the LLM response and post-processes it, to return a message that is passed to the user.

`update_chat_state(chat_state: List[dict], message) -> chat_state: List[dict]:`
    # Takes the current chat state and the new message, and creates the new chat state.

**Comment by kavitharaju** [comment]
some thoughts

1. We could consider adding __**kwargs__ to these functions to accomodate newer params needed for different technologies. For example, in the `translate_text()`, google may not need input language, but another API may need params like i/p lang, o/p lang, model_name etc. 
2. I see in `query_llm()` you are passing `model`. Is this to choose from different technologies? Then, dont we need that choice for DB and translation API? I am thinking, a field saying `technology=default_value`. Or is there a different logic where we choose which implementation of the interface is to be invoked?
3. In langchain, I think there need not be separate `create_prompt()` and  `get_results_from_query()` methods. Instead, the `query_llm()` would need params to accept question and chat history. I guess, **kwargs will allow this.
4. BTW, are you not considering chat history in `get_results_from_query()`?
5. Have you considered using websockets instead of http APIs? In my prototype, I see, the LLM's response come as stream and takes a while to get the full response. Using websocket I was able to get the streamed response to user in real time not requiring him to wait for several seconds. I don't know if this applies for our plan where we need post processing of response though...

**Comment by woodwardmw** [comment]
Thanks Kavitha, good thoughts. My responses:

> We could consider adding **kwargs to these functions to accomodate newer params needed for different technologies. For example, in the translate_text(), google may not need input language, but another API may need params like i/p lang, o/p lang, model_name etc.

Yes, sounds good.

> I see in query_llm() you are passing model. Is this to choose from different technologies? Then, dont we need that choice for DB and translation API? I am thinking, a field saying technology=default_value. Or is there a different logic where we choose which implementation of the interface is to be invoked?

Yes, we probably should do that for DB and translation API too. I was assuming those would be set for the demo, but probably best to have them as variables from the start, to make it easier to offer other options later.

> In langchain, I think there need not be separate create_prompt() and get_results_from_query() methods. Instead, the query_llm() would need params to accept question and chat history. I guess, **kwargs will allow this.

Maybe we should combine those into one function then.

> BTW, are you not considering chat history in get_results_from_query()?

Oh, yes I am doing that - good catch. I'll update this to reflect the fact that the results also incorporate the history.

> Have you considered using websockets instead of http APIs? In my prototype, I see, the LLM's response come as stream and takes a while to get the full response. Using websocket I was able to get the streamed response to user in real time not requiring him to wait for several seconds. I don't know if this applies for our plan where we need post processing of response though...

I know nothing about websockets, but would love to get the response in real-time and not wait! So I would be very happy to learn how to do that...!

**Comment by kavitharaju** [comment]
A high-level description of what we discussed and decided in the meeting...

- Use class based structure for defining interfaces and their implementations. Following are the interface classes we can begin with:
  - Embedding (Implemention: OpenAI etc)
  - VectorDB (Implementation: ChromaDB etc)
  - LmmFramework (Implementation: Vanilla, Langchain)
- Define different pipelines that stacks different technologies. To start with, we can have
  - Vanilla based pipeline
  - LangChain Based Pipeline
- Directory structure
   ```
  assistant.bible/app/core
  ├── embedding/
          ├── interface.py
          ├── openai.py
  ├── vectordb/
          ├── interface.py
          ├── chroma.py
  ├── lmmframework/
          ├── interface.py
          ├── vanilla.py
          ├── langchain.py
  ├── pipeline/
          ├── interface.py
          ├── langchain_based.py
          ├── vanilla_based.py
  ├── auth/
          ├── supabase.py
  ```
  :warning: The naming of the interface and class files are just proposals. If python/pylint etc has naming conventions or restrictions related to it, they need to be adhered to.
This just gives the structure. What goes inside each interface, like the method signatures etc can be discussed in separate issues in detail, as needed.

**Comment by woodwardmw** [comment]
That looks good to me. I'll make a PR with this structure.
